# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/yeqingsong/YQSComponentTest-.git'
source 'https://github.com/CocoaPods/Specs.git'
target 'basicSort' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for basicSort
#  pod 'JZDFilterAlertView', '~> 0.1.4'
   pod 'JZDFilterAlertView', '0.1.3'
  target 'basicSortTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'basicSortUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
