# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IJKMedia' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for IJKMedia
  pod 'LFLiveKit'
  target 'IJKMediaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IJKMediaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
